# Generated by Django 3.2.3 on 2023-03-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prize',
            field=models.IntegerField(default=499),
        ),
        migrations.AddField(
            model_name='post',
            name='product_name',
            field=models.CharField(default='shirt', max_length=50),
        ),
    ]
