# Generated by Django 3.2.3 on 2023-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
