# Generated by Django 3.2.3 on 2023-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20230308_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_id',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
